export const CFG = {
  // Canvas dimensions
  W: 640,
  H: 480,

  // Colors
  GREEN: '#00a000',
  WHITE: '#ffffff',
  BLACK: '#000000',
  TAN: '#d2b48c',
  COOP_FILL: '#007a00',
  COOP_STROKE: '#004d00',

  // Coop geometry
  COOP_SIZE: 60,
  COOP_WALL: 8,
  COOP_DOOR_W: 26,
  COOP_DOOR_DEPTH: 12,
  COOP_OFFSET_Y: 0.10,
  COOP_PAD: 0.8,

  // Chickens
  COUNT: 28,
  SIZE: 18,
  P_CHICK: 0.22,
  P_ROOSTER: 0.14,
  CHICK_SIZE_DELTA: -2,
  ROOSTER_SIZE_DELTA: 2,

  // Seed (feed)
  SEED_SIZE: 6,
  SCATTER_RADIUS: 44,
  SCATTER_MIN_CHICKENS: 4,
  SCATTER_CHANCE_PER_SEC: 0.85,
  SCATTER_IMPULSE_MIN: 55,
  SCATTER_IMPULSE_MAX: 130,
  SEED_FRICTION: 0.88,
  SEEDS_PER_DROP: 1,
  SEED_SPREAD: 26,
  GRAVITY: 1200,
  SEED_EAT_TIME: 1.0,
  EAT_RADIUS: 14,

  // Seed polish
  SEED_CLUSTERS: 3,
  SEED_CLUSTER_RADIUS: 16,
  PECK_TIME: 0.16,
  PECK_SLOW: 0.70,
  PECK_JITTER: 0.80,

  // Wander feel
  CENTER_PULL: 0.14,
  WANDER: 3.5,
  DAMPING: 0.90,
  MAX_SPEED: 650,

  // Impulses
  IMPULSE_CHANCE: 0.18,
  IMPULSE_SCALE: 2.0,

  // Reaction + chase
  REACTION_MAX: 10.0,
  CHASE_VEL_GAIN: 4.2,

  // Zigzag motion
  ZIGZAG_FREQ_MIN: 1.2,
  ZIGZAG_FREQ_MAX: 3.5,
  ZIGZAG_AMP_WANDER: 0.35,
  ZIGZAG_AMP_CHASE: 0.25,

  // Collision avoidance
  SEPARATION_DIST_CHASE: 18, // SIZE * 0.95 (SIZE is 18)
  SEPARATION_DIST_WANDER: 27.9, // SIZE * 1.55
  SEPARATION_STRENGTH_CHASE: 1200,
  SEPARATION_STRENGTH_WANDER: 2200,

  // Socialness
  SOCIAL_RANGE: 155,
  SOCIAL_MIN: 42,
  SOCIAL_STRENGTH: 95,

  // Simple flocking
  FLOCK_RANGE: 175,
  ALIGN_STRENGTH: 0.35,
  COHESION_STRENGTH: 25,
  PERSONAL_SPACE: 43.2, // SIZE * 2.4
  PERSONAL_SPACE_STRENGTH: 650,

  // Temperament flipping
  ISOLATED_NEIGHBOR_RADIUS: 150,
  ISOLATED_FOR: 8.0,
  CLUSTER_RADIUS: 90,
  CLUSTER_NEIGHBORS: 5,
  CLUSTERED_FOR: 6.0,
  TEMPERAMENT_COOLDOWN: 8.0,

  // Random mutations
  MUTATION_CHANCE_PER_SEC: 0.010,
  MUTATION_SCALE: 0.22,

  // Random panic runs
  PANIC_CHANCE_PER_SEC: 0.006,
  PANIC_DURATION_MIN: 0.45,
  PANIC_DURATION_MAX: 1.15,
  PANIC_SPEED_MULT: 1.55,

  // Panic style mix
  PANIC_P_LINEAR: 0.40,
  PANIC_P_CIRCULAR: 0.22,
  PANIC_P_WAVY: 0.23,
  PANIC_P_TO_CHICKEN: 0.15,

  // Circular panic
  PANIC_CIRCLE_RADIUS_MIN: 70,
  PANIC_CIRCLE_RADIUS_MAX: 180,
  PANIC_CIRCLE_OMEGA_MIN: 3.0,
  PANIC_CIRCLE_OMEGA_MAX: 7.5,

  // Wavy panic
  PANIC_WAVE_AMP_MIN: 40,
  PANIC_WAVE_AMP_MAX: 120,
  PANIC_WAVE_FREQ_MIN: 3.0,
  PANIC_WAVE_FREQ_MAX: 10.0,

  // Fleeing
  FLEE_DETECT_RADIUS: 220,
  FLEE_DURATION_MIN: 0.40,
  FLEE_DURATION_MAX: 1.10,
  FLEE_TARGET_DIST_MIN: 160,
  FLEE_TARGET_DIST_MAX: 360,
  FLEE_SPEED_MULT: 1.35,

  // Skid
  SKID_TRIGGER: 26,
  SKID_TIME_MIN: 0.12,
  SKID_TIME_MAX: 0.28,
  SKID_DAMPING: 0.97,

  // Startle on collision
  RUN_STARTLE_SPEED: 340,
  STARTLE_COLLISION_DIST: 39.6, // SIZE * 2.2
  STARTLE_COOLDOWN: 0.85,
  STARTLE_IMPULSE: 520,

  // Despawn/spawn zones
  DESPAWN_RADIUS: 20,
  SPAWN_RADIUS: 30,
  ZONE_SPACING: 50,

  // Pathfinding around coop
  COOP_AVOID_RADIUS: 80,
  COOP_AVOID_STRENGTH: 300,

  // Fatigue system
  FATIGUE_RATE: 0.1,
  REST_DURATION_MIN: 15.0,
  REST_DURATION_MAX: 30.0,
  FATIGUE_RECOVERY_RATE: 2.0,

  // Feather puff system
  PUFF_DOWN_COUNT: [10, 18],
  PUFF_FEATHER_COUNT: [1, 2],
  PUFF_SPEED_DOWN: [80, 220],
  PUFF_SPEED_FEATHER: [60, 180],
  PUFF_LIFE_DOWN: [0.5, 1.2],
  PUFF_LIFE_FEATHER: [0.8, 1.8],
  PUFF_BIAS: 0.75,
  PUFF_SPREAD: 0.9,
  PUFF_GRAV: 380,
  PUFF_DRAG: 0.90,
  PUFF_SETTLE_SPEED: 18,
  PUFF_SETTLE_LIFE_MULT: 1.9,
};
